/** 34 tỉnh/thành phố sau sáp nhập hành chính (hiệu lực từ 12/6/2025, Nghị quyết 202/2025/QH15) */
export const VIETNAM_CITIES = [
  'Hà Nội',
  'Lai Châu',
  'Điện Biên',
  'Sơn La',
  'Lào Cai',
  'Tuyên Quang',
  'Lạng Sơn',
  'Cao Bằng',
  'Quảng Ninh',
  'Hải Phòng',
  'Bắc Ninh',
  'Thái Nguyên',
  'Phú Thọ',
  'Hưng Yên',
  'Ninh Bình',
  'Thanh Hóa',
  'Nghệ An',
  'Hà Tĩnh',
  'Quảng Trị',
  'Huế',
  'Đà Nẵng',
  'Quảng Ngãi',
  'Gia Lai',
  'Khánh Hòa',
  'Lâm Đồng',
  'Đắk Lắk',
  'TP. Hồ Chí Minh',
  'Đồng Nai',
  'Tây Ninh',
  'Cần Thơ',
  'Vĩnh Long',
  'Đồng Tháp',
  'An Giang',
  'Cà Mau',
];